spring:
  profiles:
    active: dev
---
server:
  port: 8080
  servlet:
    context-path: /gan
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  profiles: dev
---
server:
  port: 8081
spring:
  profiles: test
---